culinary_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.main, name="main"),
    path("recipes/", views.recipe, name="recipe"),
    path("recipes/<int:recipe_id>/", views.detail, name="detail"),
    path("recipes/delete/<int:recipe_id>/", views.delete_main, name="delete_main"),
    path(
        "recipes/delete_conf/<int:recipe_id>/",
        views.delete_conf,
        name="delete_conf",
    ),
    path(
        "recipes/recipe-confirmation/",
        views.recipe_conf,
        name="recipe_confirmation",
    ),
    path("recipes/recipe-confirmation/<int:recipe_id>/", views.confirm, name="confirm"),
    path("tag/<slug:tag_slug>/", views.recipe_list, name="tag"),
    path("recipe/<int:recipe_id>/rate/", views.rate_recipe, name="rate_recipe"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

recipes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    # name = models.CharField(max_length=50, unique=True, null=False)

    # def __str__(self):
    #     return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)
    image = CloudinaryField(
        "image_recipe", null=False, folder="CulinaryHub/", default=""
    )
    created_at = models.DateTimeField(default=timezone.now, null=False)
    tag_field = models.CharField(max_length=100, null=False, default="recipe")
    confirmation = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="recipes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    average_rating = models.FloatField(
        default=0.00, validators=[MinValueValidator(0), MaxValueValidator(5)]
    )

    def __str__(self):
        return self.title

    def update_average_rating(self):
        ratings = self.rating_set.all()
        if ratings:
            self.average_rating = sum(r.value for r in ratings) / len(ratings)
        else:
            self.average_rating = 0
        self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.tag_field:
            current_tags = set(self.tags.values_list("name", flat=True))
            new_tags = set(
                tag.strip().lower() for tag in self.tag_field.split(",") if tag.strip()
            )

            # Remove tags that are no longer in tag_field
            tags_to_remove = current_tags - new_tags
            for tag_name in tags_to_remove:
                tag = Tag.objects.get(name=tag_name)
                self.tags.remove(tag)

            # Add new tags
            for tag_name in new_tags:
                tag, created = Tag.objects.get_or_create(name=tag_name)
                self.tags.add(tag)

    def get_tags(self):
        return ", ".join(tag.name for tag in self.tags.all())

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     tags = self.tag_field.split(",")
    #     for tag_name in tags:
    #         tag_name = tag_name.strip()
    #         tag, _ = Tag.objects.get_or_create(name=tag_name)
    #         self.tags.add(tag)


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)
    value = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(
        default=timezone.now,
    )

    class Meta:
        unique_together = ("user", "recipe")

recipes/forms.py
from django.forms import CharField, ModelForm
from .models import Recipe
from cloudinary.forms import CloudinaryFileField


class RecipeForm(ModelForm):
    title = CharField(label="Title", required=True)
    description = CharField(label="Description", required=True)
    tag_field = CharField(label="Tags", required=False)
    image = CloudinaryFileField(
        options={
            "folder": "CulinaryHub/",
            "use_filename": True,
            "unique_filename": False,
            "overwrite": True,
            "transformation": [{"width": 300, "height": 300, "crop": "fill"}],
        }
    )

    class Meta:
        model = Recipe
        fields = ["title", "description", "tag_field", "image"]

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Avg, Count
from recipes.forms import RecipeForm
from recipes.models import Recipe, Tag, Rating


def is_staff(user):
    return user.is_authenticated and user.is_staff


def main(request):
    # Get the 3 most recently added recipes
    latest_recipes = Recipe.objects.filter(confirmation=True).order_by("-created_at")[
        :3
    ]

    # Get the 3 highest rated recipes
    top_rated_recipes = (
        Recipe.objects.filter(confirmation=True)
        .annotate(avg_rating=Avg("rating__value"), num_ratings=Count("rating"))
        .filter(num_ratings__gt=0)
        .order_by("-avg_rating")[:3]
    )

    context = {
        "latest_recipes": latest_recipes,
        "top_rated_recipes": top_rated_recipes,
    }
    return render(request, "recipes/index.html", context)


# def main(request):
#     recipes = Recipe.objects.filter(confirmation=True)
#     return render(request, "recipes/index.html", {"recipes": recipes})


@login_required
def recipe(request):
    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            tag_length = len(form.cleaned_data["tag_field"].split(","))
            if tag_length > 7:
                form.add_error("tag_field", "Too many tags")
                return render(request, "recipes/recipe.html", {"form": form})
            form.save()
            new_recipe = form.save(commit=False)
            new_recipe.user = request.user
            new_recipe.save()
            return redirect("recipes:main")
        else:
            return render(request, "recipes/recipe.html", {"form": form})

    return render(request, "recipes/recipe.html", {"form": RecipeForm()})


# def detail(request, recipe_id):
#     recipe_page = get_object_or_404(Recipe, pk=recipe_id)
#     return render(request, "recipes/detail.html", {"recipe": recipe_page})


def detail(request, recipe_id):
    recipe_page = get_object_or_404(Recipe, id=recipe_id)
    user_has_rated = False
    if request.user.is_authenticated:
        user_has_rated = Rating.objects.filter(
            user=request.user, recipe=recipe_page
        ).exists()

    context = {"recipe": recipe_page, "user_has_rated": user_has_rated}
    return render(request, "recipes/detail.html", context)


@login_required
def delete_main(request, recipe_id):
    recipe_page = get_object_or_404(Recipe, pk=recipe_id)
    recipe_page.delete()
    return redirect("recipes:main")


@login_required
def delete_conf(request, recipe_id):
    recipe_page = get_object_or_404(Recipe, pk=recipe_id)
    recipe_page.delete()
    return redirect("recipes:recipe_confirmation")


@user_passes_test(is_staff)
@login_required
def recipe_conf(request):
    recipes = Recipe.objects.filter(confirmation=False)
    return render(request, "recipes/recipe-conf.html", {"recipes": recipes})


@login_required
def confirm(request, recipe_id):
    recipe_page = get_object_or_404(Recipe, pk=recipe_id)
    recipe_page.confirmation = True
    recipe_page.save()
    return redirect("recipes:recipe_confirmation")


def recipe_list(request, tag_slug=None):
    recipes = Recipe.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        recipes = recipes.filter(tags=tag)

    return render(request, "recipes/recipe_list.html", {"recipes": recipes, "tag": tag})


@login_required
def rate_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == "POST" and request.user != recipe.user:
        # Check if the user has already rated this recipe
        existing_rating = Rating.objects.filter(
            user=request.user, recipe=recipe
        ).first()
        if not existing_rating:
            value = int(request.POST.get("rating", 0))
            if 1 <= value <= 5:
                Rating.objects.create(user=request.user, recipe=recipe, value=value)
                recipe.update_average_rating()
    return redirect("recipes:detail", recipe_id=recipe_id)

recipes/templates/recipes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>    
    <title>Culinary Hub</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/style.css' %}">
</head>
<body>
<main>
    <div class="container">
        <div class="header-box">            
            <a href="{% url 'recipes:main' %}"><img src="{% static 'recipes/main-logo.png' %}" alt="Go to home page"></a>
        
            {% if user.is_authenticated %}
            <ul class="header-menu">
                <li>Welcome, <b>{{ user.username }}!</b></li>
                <li class="dash">|</li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li class="dash">|</li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul class="header-menu">
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li class="dash">|</li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}            
        </div>
        <div>
            <ul class="main-menu">
                {% if user.is_authenticated %}                
                <li><a href="{% url 'recipes:recipe' %}">Add new recipe</a></li>
                <li class="dash">|</li>
                {% if user.is_staff %}
                <li><a href="{% url 'recipes:recipe_confirmation' %}">Confirm  recipes</a></li>
                <li  class="dash">|</li>
                {% endif %}
                {% endif %}                
            </ul>
        </div>
        <div class="row">
            <div class="column1">
                {% block content %} {% endblock %}
            </div>
            <div class="column2">
                <div class="tag-cloud">
                    {% for tag in tags %}
                    <a href="{% url 'recipes:tag' tag.slug %}" style="font-size: {{ tag.size }}em;">
                        {{ tag.name }}
                    </a>
                    {% endfor %}
                </div>
            </div>
            
        </div>
    </div>
</main>
</body>
</html>

recipes/templates/recipes/detail.html
{% extends "recipes/base.html" %}

{% block content %}

<h1>{{recipe.title}}</h1>
<p>Description: <b>{{recipe.description}}</b></p>
<p>Time of creation: <kbd>{{recipe.created_at}}</kbd></p>
<p>Tags: <small> {{ recipe.tag_field }} </small></p>

<div class="average-rating">
    Average Rating: {% include 'recipes/stars.html' with rating=recipe.average_rating %}
</div>

{% if user.is_authenticated and user != recipe.user %}
    {% if not user_has_rated %}
        <form method="post" action="{% url 'recipes:rate_recipe' recipe.id %}">
            {% csrf_token %}
            <label for="rating">Rate this recipe:</label>
            <select name="rating" id="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <button type="submit">Submit Rating</button>
        </form>
    {% endif %}
{% endif %}


{% if user.is_authenticated and user.is_staff %}
    {% if recipe.confirmation == False %}
    <a href="{% url 'recipes:confirm'  recipe.id %}" role="button">CONFIRM</a>
    <a href="{% url 'recipes:delete_conf'  recipe.id %}" role="button">DELETE</a>
    {% else %}
    <a href="{% url 'recipes:delete_main' recipe.id %}" role="button" class="contrast">DELETE</a>
    {% endif %}
{% endif %}
{% endblock %}

recipes/templates/recipes/index.html
{% extends "recipes/base.html" %}
{% block content %}
<h2>Latest Recipes</h2>
<div class="last-3-recipes">
    {% for recipe in latest_recipes %}
    <a href="{% url 'recipes:detail' recipe.id %}">
        <div class="recipe-item">
            {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe-image">
            {% endif %}
            <h3 class="recipe-title">{{ recipe.title }}</h3>            
        </div>
    </a>
    {% endfor %}
</div>

<h2>Top Rated Recipes</h2>
<div class="top-3-recipes">
    {% for recipe in top_rated_recipes %}
    <a href="{% url 'recipes:detail' recipe.id %}">
        <div class="recipe-item">
            {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe-image">
            {% endif %}
            <h3 class="recipe-title">{{ recipe.title }}</h3>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

recipes/templates/recipes/recipe-conf.html
{% extends "recipes/base.html" %}
{% block content %}
    <div class="last-3-recipes">
        {% for recipe in recipes %}
        <a href="{% url 'recipes:detail' recipe.id %}">
            <div class="recipe-item">
                {% if recipe.image %}
                <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe-image">
                {% endif %}
                <h2 class="recipe-title">{{ recipe.title }}</h2>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

recipes/templates/recipes/recipe.html
{% extends "recipes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'recipes:recipe' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="padding: 10px">
        <label for="{{ form.title.id_for_label }}">Recipe title:</label>
        {{ form.title }}
        <span>{{ form.title.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="{{ form.description.id_for_label }}">Recipe description:</label>
        {{ form.description }}
        <span>{{ form.description.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="{{ form.tag_field.id_for_label }}">Tags:</label>
        {{ form.tag_field }}
        <span>{{ form.tag_field.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="{{ form.image.id_for_label }}">Image:</label>
        {{ form.image }}
        <span>{{ form.image.errors }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends "recipes/base.html" %}
{% block content %}
<div class="last-3-recipes">
    {% for recipe in recipes %}
    <a href="{% url 'recipes:detail' recipe.id %}">
        <div class="recipe-item">
            {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe-image">
            {% endif %}
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

recipes/templates/recipes/stars.html
{% with ''|center:5 as range %}
{% for _ in range %}
    {% if forloop.counter <= rating %} 
        <span class="star filled">★</span>
    {% else %}
        <span class="star">☆</span>
    {% endif %}
{% endfor %}
{% endwith %}